/**
 * The guard hook (PreToolUse Write|Edit): the upstream-first boundary that
 * refuses a consumer brand's edit to a generated file or a shadow copy of a
 * framework file.
 * Run: node --test scripts/agent-plugins-guard.test.js
 */
const { test } = require('node:test');
const assert = require('node:assert/strict');
const { execFileSync, spawnSync } = require('child_process');
const fs = require('fs');
const os = require('os');
const path = require('path');

const { ROOT, readJson, project, brand, monorepo } = require('./agent-plugins-fixtures');

const GUARD_HOOK = path.join(ROOT, 'agent-plugins', 'claude', 'hooks', 'guard', 'run.sh');

// An Edit payload carries no content; a Write carries what is about to land —
// which is the only thing a brand-new shadow path can be judged on.
const guard = (filePath, { content, env } = {}) => spawnSync(GUARD_HOOK, {
  input: JSON.stringify({
    hook_event_name: 'PreToolUse',
    tool_name: content === undefined ? 'Edit' : 'Write',
    tool_input: content === undefined
      ? { file_path: filePath }
      : { file_path: filePath, content },
  }),
  encoding: 'utf8',
  env: { ...process.env, ...(env || {}) },
});

// The LIVE install the shadow lookup reads: node_modules/@omega.js/<framework>,
// exactly where a real brand keeps it.
const install = (dir, framework, files) => {
  for (const [rel, body] of Object.entries(files)) {
    const file = path.join(dir, 'node_modules', '@omega.js', framework, rel);
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, body);
  }
};

const write = (dir, rel, body) => {
  const file = path.join(dir, rel);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, body);
  return file;
};

const guardBrand = () => {
  const dir = brand({
    targets: {
      web: { name: 'a-brand-web', dependencies: { '@omega.js/web': '^1.0.0' } },
      backend: { name: 'a-brand-backend', dependencies: { '@omega.js/backend': '^1.0.0' } },
    },
  });
  // The REAL shapes, names and all: the guard is only as honest as the tree it
  // reads, and every one of these paths exists in the shipped packages.
  install(dir, 'web', {
    'core/_layouts/blueprint/index.html': '<html></html>\n',
    'core/_includes/core/head.html': '<head></head>\n',
    'core/css/main.scss': '// core\n',
    'core/css/pages/404/index.scss': '// the 404 page sheet\n',
    'core/js/main.js': '// core main\n',
    'core/js/pages/blog.js': '// a page module, not a shadow\n',
    'themes/classy/_includes/marketing/nav.html': '<nav></nav>\n',
    'themes/classy/css/base/_type.scss': '// type\n',
    'themes/base/_sections/marketing/hero/section.html': '<section></section>\n',
    'defaults/pages/index.md': '# home\n',
    'defaults/pages/about.md': '# about\n',
    'defaults/pages/pricing.md': '# pricing\n',
    'defaults/pages/contact.md': '# contact\n',
  });
  install(dir, 'backend', {
    'templates/firestore.framework.rules': '// the framework half\n',
    'templates/firestore.rules': '// the seed a brand owns after setup\n',
    'dist/omega/routes/general/email/post.js': 'module.exports = {};\n',
    'dist/omega/schemas/general/email/post.js': 'module.exports = {};\n',
    'dist/omega/index.js': '// the Omega class\n',
    'dist/omega/libraries/email/index.js': '// framework internals\n',
  });
  return dir;
};

test('guard: generated and vendored files are refused outright', () => {
  const dir = guardBrand();
  const cases = [
    ['node_modules/@omega.js/web/core/_includes/core/head.html', /node_modules/],
    ['targets/web/dist/index.html', /dist/],
    ['targets/backend/database.rules.json', /omega\.json5|setup/],
  ];
  for (const [rel, names] of cases) {
    const result = guard(path.join(dir, rel));
    assert.equal(result.status, 2, `${rel} was let through`);
    assert.match(result.stderr, /omega:guard/, `${rel} refusal lacks the hook name`);
    assert.match(result.stderr, names, `${rel} refusal does not name the real source to edit`);
  }
  fs.rmSync(dir, { recursive: true, force: true });
});

test('guard: a generated header refuses the whole file', () => {
  const dir = guardBrand();
  const marked = write(dir, 'targets/web/src/generated.html',
    '<!-- GENERATED FILE — DO NOT EDIT -->\n<p>x</p>\n');
  const banner = write(dir, 'targets/web/src/banner.html',
    '<!-- Generated by @omega.js/web -->\n<p>x</p>\n');

  for (const file of [marked, banner]) {
    const result = guard(file);
    assert.equal(result.status, 2, `${file} was let through`);
    assert.match(result.stderr, /omega:guard/);
  }
  fs.rmSync(dir, { recursive: true, force: true });
});

test('guard: a shadow copy is refused and names the framework file it mirrors', () => {
  const dir = guardBrand();
  // One row per real override-layer root — the MECHANISM lanes only.
  const table = [
    ['targets/web/src/_layouts/blueprint/index.html', '@omega.js/web/core/_layouts/blueprint/index.html'],
    ['targets/web/src/_includes/core/head.html', '@omega.js/web/core/_includes/core/head.html'],
    ['targets/web/src/_includes/marketing/nav.html', '@omega.js/web/themes/classy/_includes/marketing/nav.html'],
    ['targets/web/src/_sections/marketing/hero/section.html', '@omega.js/web/themes/base/_sections/marketing/hero/section.html'],
    ['targets/web/src/assets/css/pages/404/index.scss', '@omega.js/web/core/css/pages/404/index.scss'],
    ['targets/web/src/assets/css/base/_type.scss', '@omega.js/web/themes/classy/css/base/_type.scss'],
    ['targets/backend/firestore.framework.rules', '@omega.js/backend/templates/firestore.framework.rules'],
    ['targets/backend/src/routes/general/email/post.js', '@omega.js/backend/dist/omega/routes/general/email/post.js'],
    ['targets/backend/src/schemas/general/email/post.js', '@omega.js/backend/dist/omega/schemas/general/email/post.js'],
  ];

  for (const [rel, mirrored] of table) {
    write(dir, rel, 'a hand-written copy\n');
    const result = guard(path.join(dir, rel));
    assert.equal(result.status, 2, `${rel} was let through`);
    assert.match(result.stderr, /omega:guard/);
    assert.ok(result.stderr.includes(mirrored), `${rel} refusal does not name ${mirrored}`);
    assert.match(result.stderr, /upstream-first/, `${rel} refusal does not say to file a framework issue`);
    assert.match(result.stderr, /omega:consumer-override:/, `${rel} refusal does not name the marker`);
  }
  fs.rmSync(dir, { recursive: true, force: true });
});

test('guard: content is never guarded — a brand page named like a default is its own', () => {
  const dir = guardBrand();
  // src/pages/ is the DESIGNED place for a brand's own copy: every page the
  // framework ships a default for is a page a brand is expected to write.
  for (const name of ['index.md', 'about.md', 'pricing.md', 'contact.md']) {
    const rel = `targets/web/src/pages/${name}`;
    assert.equal(guard(write(dir, rel, '# our own page\n')).status, 0, `${rel} was refused`);
    assert.equal(guard(path.join(dir, rel), { content: '# a fresh page\n' }).status, 0, `a new ${rel} was refused`);
  }
  fs.rmSync(dir, { recursive: true, force: true });
});

test('guard: the documented consumer entry files are free, and a union lane is not a shadow', () => {
  const dir = guardBrand();
  const free = [
    // theming.md tier 1 / the web guide's REPLACE-with-extend lane
    'targets/web/src/assets/css/main.scss',
    'targets/web/src/assets/js/main.js',
    // page and layout modules are a UNION: every layer's file runs
    'targets/web/src/assets/js/pages/blog.js',
    // not a layer root at all
    'targets/web/src/js/main.js',
    // the brand's authored Cloud Functions entry
    'targets/backend/src/index.js',
  ];
  for (const rel of free) {
    assert.equal(guard(write(dir, rel, 'brand content\n')).status, 0, `${rel} was refused`);
  }
  fs.rmSync(dir, { recursive: true, force: true });
});

test('guard: the marker in the first five lines passes the same file', () => {
  const dir = guardBrand();
  const rel = 'targets/web/src/_includes/core/head.html';
  assert.equal(guard(write(dir, rel, 'a hand-written copy\n')).status, 2, 'the shadow was not refused to begin with');

  write(dir, rel, '<!-- omega:consumer-override: this brand ships its own head -->\n<head></head>\n');
  assert.equal(guard(path.join(dir, rel)).status, 0, 'the marker did not let the edit through');

  // Below the first five lines it is a comment, not a marker.
  write(dir, rel, '1\n2\n3\n4\n5\n// omega:consumer-override: too late\n');
  assert.equal(guard(path.join(dir, rel)).status, 2, 'a marker on line six counted');
  fs.rmSync(dir, { recursive: true, force: true });
});

test('guard: a NEW shadow path is judged on the content being written', () => {
  const dir = guardBrand();
  const file = path.join(dir, 'targets', 'web', 'src', '_includes', 'core', 'head.html');

  const refused = guard(file, { content: '<head></head>\n' });
  assert.equal(refused.status, 2, 'a brand-new shadow include was let through');
  assert.ok(refused.stderr.includes('@omega.js/web/core/_includes/core/head.html'));

  const allowed = guard(file, { content: '{% comment %}\n  omega:consumer-override: materialized by omega customize _includes/core/head.html\n{% endcomment %}\n' });
  assert.equal(allowed.status, 0, 'the marker in the written content did not let it through');
  fs.rmSync(dir, { recursive: true, force: true });
});

test('guard: OMEGA_CONSUMER_OVERRIDE=1 skips class 2 and never class 1', () => {
  const dir = guardBrand();
  const env = { OMEGA_CONSUMER_OVERRIDE: '1' };
  const shadow = write(dir, 'targets/web/src/_includes/core/head.html', 'a hand-written copy\n');
  assert.equal(guard(shadow, { env }).status, 0, 'the env flag did not skip the shadow check');

  for (const rel of ['node_modules/@omega.js/web/core/css/main.scss', 'targets/web/dist/index.html', 'targets/backend/database.rules.json']) {
    assert.equal(guard(path.join(dir, rel), { env }).status, 2, `${rel} escaped through the env flag`);
  }
  fs.rmSync(dir, { recursive: true, force: true });
});

test('guard: plain brand files and the brand\'s own rules source are free', () => {
  const dir = guardBrand();
  const free = [
    'targets/web/src/assets/css/brand.scss',
    'targets/backend/src/routes/checkout/post.js',
    'targets/backend/firestore.rules',
    'targets/backend/storage.rules',
    'targets/backend/firebase.json',
    'README.md',
    'config/omega.json5',
  ];
  for (const rel of free) {
    assert.equal(guard(write(dir, rel, 'brand content\n')).status, 0, `${rel} was refused`);
  }
  fs.rmSync(dir, { recursive: true, force: true });
});

test('guard: the monorepo itself is never guarded', () => {
  const dir = monorepo();
  install(dir, 'web', { 'core/_includes/core/head.html': '<head></head>\n' });
  fs.mkdirSync(path.join(dir, 'brands', 'playground', 'config'), { recursive: true });
  fs.writeFileSync(path.join(dir, 'brands', 'playground', 'config', 'omega.json5'), "{\n  targets: {\n    web: { type: 'web' },\n  },\n}\n");
  write(dir, 'brands/playground/targets/web/package.json', JSON.stringify({ name: 'p', dependencies: { '@omega.js/web': '^1.0.0' } }));
  install(path.join(dir, 'brands', 'playground'), 'web', { 'core/_includes/core/head.html': '<head></head>\n' });

  for (const rel of [
    'brands/playground/targets/web/src/_includes/core/head.html',
    'packages/web/dist/index.js',
    'packages/web/core/_includes/core/head.html',
  ]) {
    assert.equal(guard(write(dir, rel, 'crew content\n')).status, 0, `${rel} was guarded inside the monorepo`);
  }
  fs.rmSync(dir, { recursive: true, force: true });
});

test('guard: a project that is not a brand, and a missing jq, fail open', () => {
  const plain = project({ name: 'somebody-else', dependencies: { react: '^19.0.0' } });
  assert.equal(guard(write(plain, 'node_modules/react/index.js', 'x\n')).status, 0);
  fs.rmSync(plain, { recursive: true, force: true });

  const nothing = fs.mkdtempSync(path.join(os.tmpdir(), 'omega-guard-bare-'));
  fs.mkdirSync(path.join(nothing, '.git'));
  assert.equal(guard(path.join(nothing, 'dist', 'index.js')).status, 0, 'a directory with no manifest was guarded');
  fs.rmSync(nothing, { recursive: true, force: true });

  // No jq: a PATH carrying every other tool the script uses, and not that one.
  const bin = fs.mkdtempSync(path.join(os.tmpdir(), 'omega-guard-bin-'));
  for (const tool of ['env', 'bash', 'cat', 'dirname', 'basename', 'head', 'grep']) {
    const real = execFileSync('command', ['-v', tool], { shell: '/bin/bash', encoding: 'utf8' }).trim();
    fs.symlinkSync(real, path.join(bin, tool));
  }
  const dir = guardBrand();
  const jqless = guard(path.join(dir, 'targets', 'web', 'dist', 'index.html'), { env: { PATH: bin } });
  assert.equal(jqless.status, 0, `no jq did not fail open: ${jqless.stderr}`);
  fs.rmSync(bin, { recursive: true, force: true });
  fs.rmSync(dir, { recursive: true, force: true });
});

test('guard: a relative file_path fails open instead of walking forever', () => {
  // No .git anywhere up the tree, which is what exposes the loop: a walk that
  // only stops at a git root never stops when `dirname` bottoms out at ".".
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'omega-guard-rel-'));
  fs.writeFileSync(path.join(dir, 'package.json'), JSON.stringify({ name: 'a-brand', dependencies: { '@omega.js/manager': '^1.0.0' } }));
  // `dirname` of a relative path bottoms out at "." and stays there, so an
  // unanchored walk never terminates. Both walks refuse a non-absolute dir.
  const result = spawnSync('timeout', ['10', GUARD_HOOK], {
    input: JSON.stringify({
      hook_event_name: 'PreToolUse',
      tool_name: 'Edit',
      tool_input: { file_path: 'targets/web/src/_includes/core/head.html' },
    }),
    cwd: dir,
    encoding: 'utf8',
  });
  assert.notEqual(result.status, 124, 'the hook spun forever on a relative path');
  assert.equal(result.status, 0, `a relative path did not fail open: ${result.stderr}`);
  fs.rmSync(dir, { recursive: true, force: true });
});

test('guard: hooks.json wires the guard as a third PreToolUse Write|Edit command', () => {
  const hooks = readJson(path.join(ROOT, 'agent-plugins', 'claude', 'hooks', 'hooks.json')).hooks;
  const entry = hooks.PreToolUse.find((h) => h.matcher === 'Write|Edit');
  assert.ok(entry, 'no PreToolUse Write|Edit entry');
  const commands = entry.hooks.map((hook) => hook.command);
  assert.ok(commands.some((command) => /hooks\/guard\/run\.sh/.test(command)), 'the guard is not registered');
});
