/**
 * playground-desktop workflow tests: what the desktop template renders through
 * `composeWorkflow` is a workflow GitHub can run, and the generator writes
 * exactly that ([#802](https://github.com/Omega-JS-Stack/omega/issues/802)).
 *
 * The file itself is NOT tracked (the rehearsal renders it per run and pushes it
 * to the snapshot repo), so every case reads the render, and the write case
 * drives the generator and reads back what it left at the root path. What the
 * pair protects: a template change that never reaches the run would leave the
 * monorepo's own release rehearsal building an older desktop than every brand.
 *
 * Run: node --test scripts/playground-desktop-workflow.test.js
 */
const { test } = require('node:test');
const assert = require('node:assert/strict');
const { execFileSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.join(__dirname, '..');
const { renderWorkflow, WORKFLOW, TARGET_PATH, WORKFLOW_NAME } = require('./playground-desktop-workflow.js');
const { workflowSecretKeys } = require('@omega.js/config/env-delivery');

// js-yaml is @omega.js/desktop's own dependency (the framework parses its
// electron-builder config with it), resolved from there so this test reads the
// version the repo already installs, never one it asks for.
const yaml = require(require.resolve('js-yaml', { paths: [path.join(ROOT, 'packages', 'desktop')] }));

const rendered = () => renderWorkflow();
const workflow = () => yaml.load(rendered());

// The steps of a job that follow its `actions/checkout`, which is where the
// composed scoping starts and where the target dir exists.
const postCheckoutSteps = (job) => {
  const checkout = (job.steps || []).findIndex((step) => String(step.uses || '').startsWith('actions/checkout'));
  return checkout === -1 ? [] : job.steps.slice(checkout + 1);
};

// The jobs that check out at all: the ones the scoping and the root install
// apply to, counted from the file rather than remembered as a number.
const checkoutJobs = (jobs) => Object.entries(jobs).filter(([, job]) => (job.steps || []).some((step) => String(step.uses || '').startsWith('actions/checkout')));

test('the generator writes the render, at the path the rehearsal snapshots', () => {
  // The generator's own write path, driven for real: the rehearsal calls it
  // before every dispatch, and a file written anywhere else is a run on a stale
  // (or missing) workflow. The path is gitignored, so this writes nothing the
  // repo tracks. Seeded with a file that is NOT the render first, so a generator
  // writing elsewhere cannot pass on the leftover of an earlier run.
  fs.writeFileSync(WORKFLOW, '# not the render\n');
  execFileSync(process.execPath, [path.join(ROOT, 'scripts', 'playground-desktop-workflow.js')], { cwd: ROOT, stdio: 'ignore' });

  assert.equal(
    fs.readFileSync(WORKFLOW, 'utf8'),
    renderWorkflow(),
    'the generator wrote something other than what it renders',
  );
});

test('it parses, it is dispatch-only, and it says what it is', () => {
  const parsed = workflow();

  assert.equal(parsed.name, WORKFLOW_NAME);
  // `on:` is YAML 1.1's `true`, and js-yaml 4 keeps the string, so accept either.
  const triggers = parsed.on || parsed[true];
  assert.deepEqual(Object.keys(triggers), ['workflow_dispatch'], 'a release run is dispatched by hand, never by a push');
  assert.equal(triggers.workflow_dispatch.inputs.platforms.default, 'all');
  assert.match(rendered(), /^# GENERATED by scripts\/playground-desktop-workflow\.js/, 'the file names its generator');
});

test('every CI-delivered key of the env schema reaches the runner', () => {
  const env = workflow().env;

  for (const key of workflowSecretKeys('desktop')) {
    assert.ok(env[key] !== undefined, `${key} is delivered to desktop but the workflow env never names it`);
  }
});

test('each job installs the monorepo at the root before it touches the target', () => {
  const jobs = workflow().jobs;
  let checked = 0;

  for (const [name, job] of checkoutJobs(jobs)) {
    const steps = postCheckoutSteps(job);
    const rootInstall = steps.findIndex((step) => step.run === 'npm install && npm run prepare --workspaces --if-present');
    const targetStep = steps.findIndex((step) => step['working-directory'] !== undefined);

    assert.notEqual(rootInstall, -1, `${name}: no root install, so the playground's file: deps would not resolve`);
    assert.ok(targetStep === -1 || rootInstall < targetStep, `${name}: the root install runs after a target step`);
    checked++;
  }

  assert.equal(checked, checkoutJobs(jobs).length, 'every job that checks out carries the root install');
});

test('every post-checkout run step is the root install or runs in the target', () => {
  for (const [name, job] of Object.entries(workflow().jobs)) {
    for (const step of postCheckoutSteps(job)) {
      if (step.run === undefined || step.run.startsWith('npm install &&')) {
        continue;
      }

      assert.equal(step['working-directory'], TARGET_PATH, `${name}: an unscoped step would run at the repo root: ${step.run}`);
    }
  }
});

test('no target step runs `npm ci`, which has no lockfile to read there', () => {
  for (const [name, job] of Object.entries(workflow().jobs)) {
    for (const step of postCheckoutSteps(job)) {
      if (step['working-directory'] !== TARGET_PATH || step.run === undefined) {
        continue;
      }

      // npm reads the lockfile of the nearest workspace ROOT, the brand dir, and
      // that lockfile is not committed, so `npm ci` in the target dies on the
      // runner. A template that respells its install step has to fail HERE.
      assert.doesNotMatch(step.run, /\bnpm ci\b/, `${name}: a target step calls npm ci; the generator's rewrite missed it: ${step.run}`);
    }
  }
});

test('the run builds and tests nothing, so no job is a Test job or waits on one', () => {
  const jobs = workflow().jobs;
  // GitHub takes `needs` as a string or as a list; the graph is the same.
  const needsOf = (job) => [].concat(job.needs || []);

  assert.ok(!('test' in jobs), 'CI is dispatch-only and builds; the suite runs on the developer machine');
  for (const [name, job] of Object.entries(jobs)) {
    assert.ok(!needsOf(job).includes('test'), `${name} waits on a job that does not exist`);
  }

  assert.deepEqual(needsOf(jobs.build), ['setup']);
  assert.deepEqual(needsOf(jobs.finalize), ['setup', 'build', 'windows-sign']);
  // finalize runs under `always()`, where a failed or skipped need still
  // reaches the `if`, so the gate names the result it wants.
  assert.doesNotMatch(jobs.finalize.if, /needs\.test\.result/);
  assert.match(jobs.finalize.if, /needs\.build\.result == 'success'/);
});

test('windows-sign keeps the self-hosted EV-token runner', () => {
  const job = workflow().jobs['windows-sign'];

  assert.match(job['runs-on'], /"self-hosted","windows","ev-token"/);
  assert.equal(job.defaults.run.shell, 'cmd');
});
