#!/usr/bin/env bash
# omega:guard — PreToolUse (Write|Edit) hook
# The upstream-first boundary ([#452](https://github.com/Omega-JS-Stack/omega/issues/452)):
# inside a CONSUMER BRAND, an edit to a framework-owned file is refused, because
# a framework hole filled with a brand patch is a hole every later brand digs
# again. Two classes, treated differently:
#   1. generated or vendored (node_modules, dist, a generated header, the
#      OMEGA-managed database.rules.json) — hard refusal, no escape hatch; the
#      message names the real source to edit.
#   2. shadow copies — a brand file whose path mirrors a file the installed
#      framework ships through its OVERRIDE LAYER, read from the live install.
#      Refused with the upstream-first message and two exits: the in-file
#      `omega:consumer-override:` marker, or OMEGA_CONSUMER_OVERRIDE=1.
# The monorepo itself is exempt — packages/ is the framework's source and
# brands/ are the crew's own fixtures. Fails open on anything unexpected.

set -euo pipefail

input=$(cat)

command -v jq >/dev/null 2>&1 || exit 0

file_path=$(jq -r '.tool_input.file_path // ""' <<<"$input" 2>/dev/null || true)
[ -n "$file_path" ] || exit 0
# Only a Write carries content — which is the only thing a brand-new shadow
# path can be judged on, since there is no file to read the marker out of yet.
content=$(jq -r '.tool_input.content // ""' <<<"$input" 2>/dev/null || true)

skills_lib="$(dirname "${BASH_SOURCE[0]}")/../lib/omega-skills.sh"
[ -r "$skills_lib" ] || exit 0
# shellcheck source-path=SCRIPTDIR source=../lib/omega-skills.sh
. "$skills_lib"

# --- scope: a consumer brand, and never this monorepo ----------------------
# The monorepo walk runs to the git root on its own, because a brand FIXTURE
# under brands/ answers the brand walk long before the monorepo root is reached.
in_monorepo() {
  local dir="$1"
  # `dirname` bottoms out at "." for a relative path and stays there forever,
  # so an unanchored walk never terminates. Nothing to resolve, fail open.
  case "$dir" in /*) ;; *) return 1 ;; esac
  while [ -n "$dir" ] && [ "$dir" != "/" ]; do
    if [ -f "$dir/package.json" ] && [ -d "$dir/packages" ] \
      && [ "$(jq -r '.name // ""' "$dir/package.json" 2>/dev/null || true)" = "omega" ]; then
      return 0
    fi
    [ -e "$dir/.git" ] && return 1
    dir=$(dirname "$dir")
  done
  return 1
}

in_monorepo "$(dirname "$file_path")" && exit 0

brand=$(omega_brand_root "$(dirname "$file_path")")
[ -n "$brand" ] || exit 0
[ -f "$brand/package.json" ] || [ -f "$brand/config/omega.json5" ] || exit 0

rel="${file_path#"$brand"/}"

refuse() {
  cat >&2
  exit 2
}

# --- class 1: generated or vendored, no escape hatch -----------------------
case "$file_path" in
  */node_modules/*)
    refuse <<EOF
omega:guard — $rel is inside node_modules (an installed @omega.js package).
A dependency bug is fixed UPSTREAM: change it in the Omega monorepo and re-link
(\`omega i local\`), or file an issue on Omega-JS-Stack/omega. Patching an
install in place is erased by the next npm install and ships to nobody.
EOF
    ;;
esac

case "$rel" in
  dist/*|*/dist/*)
    refuse <<EOF
omega:guard — $rel is build output (a dist/ tree).
Edit the SOURCE it is built from and re-run the target's build (\`npx omega build\`).
A hand edit to dist/ is gone the next time the verb runs.
EOF
    ;;
esac

if [ "$(basename "$file_path")" = "database.rules.json" ]; then
  refuse <<EOF
omega:guard — $rel carries the OMEGA-managed realtime-database rules block.
That block is generated: edit config/omega.json5 for what it reflects, and let
the target checks rewrite the file (\`npx omega test\` in the backend target).
The brand's OWN security rules source is firestore.rules, which is yours.
EOF
fi

# The header a framework writer stamps on a generated artifact. Read off the
# file on disk — the stamp is the artifact's own claim about itself.
if [ -f "$file_path" ]; then
  header=$(head -n 20 "$file_path" 2>/dev/null || true)
  if grep -q 'Generated by @omega\.js/' <<<"$header" \
    || { grep -qi 'GENERATED FILE' <<<"$header" && grep -qi 'DO NOT EDIT' <<<"$header"; }; then
    refuse <<EOF
omega:guard — $rel says in its own header that it is generated.
Edit the source it is rendered from — config/omega.json5, or the framework
template behind it — and re-run the verb that wrote it. Every edit here is
overwritten on the next build.
EOF
  fi
fi

# --- class 2: shadow copies of the framework's override layer --------------
# The target the file belongs to, and the framework that owns that target. A
# brand with no targets/ directory (a single-target repo) is its own target.
target_root="$brand"
case "$file_path" in
  "$brand"/targets/*/*)
    rest="${file_path#"$brand"/targets/}"
    target_root="$brand/targets/${rest%%/*}"
    ;;
esac

framework=""
for manifest in "$target_root/package.json" "$target_root/functions/package.json"; do
  [ -f "$manifest" ] || continue
  while read -r dep; do
    case "$dep" in
      @omega.js/web|@omega.js/backend|@omega.js/desktop|@omega.js/extension)
        framework="${dep#@omega.js/}"
        break
        ;;
    esac
  done < <(omega_manifest_deps "$manifest")
  [ -n "$framework" ] && break
done
[ -n "$framework" ] || exit 0

# Read from the LIVE install, never a hardcoded list — the knowledge has to
# match the version this brand actually runs.
install=""
for candidate in "$target_root/node_modules/@omega.js/$framework" "$brand/node_modules/@omega.js/$framework"; do
  if [ -d "$candidate" ]; then
    install="$candidate"
    break
  fi
done
[ -n "$install" ] || exit 0

rel_target="${file_path#"$target_root"/}"

# THE lookup table: `<framework>|<consumer prefix, relative to the target
# root>|<framework root, glob allowed>`. A brand path under the prefix is
# stripped of it and looked up under the framework root; a hit means the brand
# file SHADOWS that framework file. ONE row per real override-layer root.
#   web      the MECHANISM lanes, mirroring src/overrides.js overrideLanes()
#            (sections, includes, css) plus the engine's layered _layouts:
#            first-layer-wins, consumer src/ → active theme → base → core.
#            Sections live in the theme layers only (core ships none), and the
#            css lane is the one sass resolves by layer.
#            NOT here, on purpose: src/pages/ is CONTENT — the designed place
#            for a brand's own copy, so a page is never guarded — and the js
#            lane has no row at all, because page and layout modules are a
#            UNION ([#624](https://github.com/Omega-JS-Stack/omega/issues/624),
#            every layer's file runs) rather than a shadow.
#   backend  the two lanes that really replace a framework file BY NAME
#            (src/manager/index.js: a consumer route or schema of the same name
#            and method replaces the framework's), plus the framework half of
#            the rules that ships in templates/.
# desktop and extension ship NO override layer: their src/defaults/ tree is
# scaffolded once and the brand owns every file in it afterwards, so there is
# nothing there to shadow.
SHADOW_ROOTS="
web|src/_layouts/|core/_layouts/
web|src/_layouts/|themes/*/_layouts/
web|src/_includes/|core/_includes/
web|src/_includes/|themes/*/_includes/
web|src/_sections/|themes/*/_sections/
web|src/_components/|themes/*/_components/
web|src/assets/css/|core/css/
web|src/assets/css/|themes/*/css/
backend|src/routes/|src/manager/routes/
backend|src/schemas/|src/manager/schemas/
backend||templates/
"

# The files the DOCS name as the consumer's own entry, and the seeds a brand
# owns once the target checks have written them. Exempt by name, never by guesswork:
#   web      main.scss is theming.md tier 1 and main.js/first-paint.js are the
#            same REPLACE-with-extend lane in docs/web/index.md — a consumer
#            file there reaches the framework's through `omega:main`, which is
#            the documented way to own it.
#   backend  every seed in templates/ the target checks write once and never again
#            (src/cli/commands/setup-tests/ in @omega.js/backend heals each).
case "$framework/$rel_target" in
  web/src/assets/css/main.scss|web/src/assets/js/main.js|web/src/assets/js/first-paint.js)
    exit 0
    ;;
  backend/firestore.rules|backend/storage.rules|backend/firebase.json|backend/firestore.indexes.json|backend/remoteconfig.template.json|backend/public/*|backend/config/*|backend/storage-lifecycle-*.json)
    exit 0
    ;;
esac

shadow=""
while IFS='|' read -r fw prefix root; do
  [ -n "$fw" ] || continue
  [ "$fw" = "$framework" ] || continue

  sub="$rel_target"
  if [ -n "$prefix" ]; then
    case "$sub" in
      "$prefix"*) sub="${sub#"$prefix"}" ;;
      *) continue ;;
    esac
  fi
  [ -n "$sub" ] || continue

  # $root is deliberately unquoted so a themes/*/ row expands to every theme.
  for candidate in "$install"/$root"$sub"; do
    if [ -f "$candidate" ]; then
      shadow="${candidate#"$install"/}"
      break
    fi
  done
  if [ -n "$shadow" ]; then break; fi
done <<EOF
$SHADOW_ROOTS
EOF

[ -n "$shadow" ] || exit 0

# The exits. The env flag covers a whole session; the marker covers one file
# forever, and lives in the first five lines in whatever comment syntax the
# file speaks (//, #, <!--, {#, /*).
[ "${OMEGA_CONSUMER_OVERRIDE:-}" = "1" ] && exit 0

if [ -f "$file_path" ] && head -n 5 "$file_path" 2>/dev/null | grep -qF 'omega:consumer-override:'; then
  exit 0
fi
if [ -n "$content" ] && printf '%s\n' "$content" | head -n 5 | grep -qF 'omega:consumer-override:'; then
  exit 0
fi

refuse <<EOF
omega:guard — $rel shadows @omega.js/$framework/$shadow (framework-owned).
If this is a framework gap, file an issue on Omega-JS-Stack/omega instead
(upstream-first). If this brand genuinely needs its own copy, add
\`// omega:consumer-override: <reason>\` to the top of the file and retry
(OMEGA_CONSUMER_OVERRIDE=1 skips this check for the session).
EOF
