// Release task — runs electron-builder with `--publish always`, which packages AND
// uploads artifacts to the configured publish provider (GitHub Releases by default,
// generated by gulp/build-config from omega.json5's `releases` block).
//
// Auth: the GH_TOKEN env var (loaded from .env or CI secrets) authorizes the upload.
//
// Cross-platform behavior:
//   - macOS: signs + notarizes (via the afterSign hook) + uploads .dmg / .zip
//   - Linux: builds + uploads .AppImage / .deb (no signing)
//   - Windows: when OMEGA_SKIP_WIN_SIGN=true (CI macOS/linux runners), this never runs the
//              Windows target. The dedicated windows-sign job in CI handles that path.
//
// For local single-platform release runs, electron-builder targets only the host OS by default.

const path    = require('path');
const jetpack = require('fs-jetpack');
const build = require('../../build.js');

const logger = build.logger('release');

// The two warnings electron-publish prints when it uploads nothing: one per
// release (`gitHubPublisher.getOrCreateRelease` returns null with its reason)
// and one per file that never left the machine.
const SKIP_WARNINGS = ['skipped publishing', 'GitHub release not created'];

module.exports = function release(done) {
  const projectRoot = process.cwd();
  const config = path.join(require('../../utils/dist-root.js')(projectRoot), 'electron-builder.yml');

  if (!jetpack.exists(config)) {
    return done(new Error(`Missing ${config}. Run gulp/build-config first (it generates this file from omega.json5).`));
  }

  if (!process.env.GH_TOKEN) {
    logger.warn('GH_TOKEN not set — electron-builder will fail to publish to GitHub Releases.');
  }

  let builder;
  try {
    builder = require('electron-builder');
  } catch (e) {
    return done(new Error(`Could not resolve electron-builder: ${e.message}. Run \`npm i -D electron-builder\` in the consumer.`));
  }

  const relConfig = path.relative(projectRoot, config);
  logger.log(`Releasing via electron-builder (config=${relConfig}, publish=always)...`);

  // electron-publish reports a skipped upload through THIS logger and nowhere
  // else, and a release that uploaded nothing must never print a success line,
  // so the logger is a requirement of the task, not a nicety. It comes off
  // electron-builder's OWN export, which re-exports the one `builder-util`
  // instance electron-publish writes to: a bare require of `builder-util` names
  // a package this manifest never declares (#872) and could resolve a SECOND
  // copy whose log nothing ever writes to.
  recordSkippedPublishes(builder.log, () => builder.build({
    config,
    publish: 'always',
  }))
    .then(({ result, skips }) => {
      const skipped = skippedUploadError(skips);
      if (skipped) {
        logger.error(skipped.message);
        return done(skipped);
      }

      const list = (result || []).map((a) => path.relative(projectRoot, a));
      logger.log(`Released ${list.length} artifact(s):`);
      list.forEach((a) => logger.log(`  • ${a}`));
      done();
    })
    .catch((e) => {
      logger.error(`Release failed: ${e.message}`);
      done(e);
    });
};

/**
 * Run the build with electron-builder's OWN logger watched, and hand back what
 * it published NOTHING for. The promise `build()` returns resolves with the
 * local artifact paths whether or not a byte was uploaded, so the resolve value
 * says nothing about the release: the skip is announced only as a warning on
 * electron-builder's log (the `builder-util` instance it re-exports), carrying
 * the reason and the tag as fields. The wrapper
 * is put back in a `finally`, so a build that throws leaves the logger the way
 * it found it. Exported for tests.
 *
 * @param {{ warn: Function }} log - electron-builder's logger.
 * @param {Function} fn - The build to run.
 * @returns {Promise<{ result: *, skips: object[] }>} What the build resolved with, and every skip it logged.
 */
async function recordSkippedPublishes(log, fn) {
  const skips = [];
  const owned = Object.prototype.hasOwnProperty.call(log, 'warn');
  const original = log.warn;

  log.warn = function (messageOrFields, message) {
    // `warn(message)` and `warn(fields, message)` are both legal on this logger.
    const text = String(message === undefined ? messageOrFields : message);
    const fields = message === undefined ? {} : (messageOrFields || {});
    if (SKIP_WARNINGS.some((warning) => text.includes(warning))) {
      skips.push({ message: text, ...fields });
    }
    return original.call(this, messageOrFields, message);
  };

  try {
    const result = await fn();
    return { result, skips };
  } finally {
    if (owned) {
      log.warn = original;
    } else {
      delete log.warn;
    }
  }
}

/**
 * The verdict on a build's recorded skips: a release that uploaded nothing is a
 * failed release, named by electron-builder's own reason. Exported for tests.
 *
 * @param {object[]} skips - What recordSkippedPublishes collected.
 * @returns {Error|null} The failure, or null when everything published.
 */
function skippedUploadError(skips) {
  if (skips.length === 0) {
    return null;
  }

  const reason = skips.find((skip) => skip.reason)?.reason || 'electron-builder gave no reason';
  const tag = skips.find((skip) => skip.tag)?.tag || 'the configured tag';
  const files = skips.map((skip) => skip.file).filter(Boolean);
  const what = files.length > 0 ? `${files.length} artifact(s) (${files.join(', ')})` : 'every artifact';

  return new Error(`Nothing was uploaded: electron-builder skipped publishing ${what} to ${tag} (${reason}). Bump the version in package.json: a release that already exists is never re-uploaded.`);
}

module.exports.recordSkippedPublishes = recordSkippedPublishes;
module.exports.skippedUploadError = skippedUploadError;
